apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: create-win-vm-and-run-ansible-pipelinerun-
  namespace: kubevirt
spec:
  pipelineRef:
    name: create-win-vm-and-run-ansible
  params:
    - name: playbookGitRepoURL
      value: https://github.com/0xFelix/ansible-integration-demo.git
    - name: playbookGitRevision
      value: addc
    - name: playbookFilename
      value: member.yml
  workspaces:
    - name: ansible
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  taskRunSpecs:
    - pipelineTaskName: create-vm-from-template
      taskServiceAccountName: create-vm-from-template-task
    - pipelineTaskName: wait-for-vmi-status
      taskServiceAccountName: wait-for-vmi-status-task
status: {}
