collections:
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.windows
    version: 1.10.0
  - name: chocolatey.chocolatey
    version: 1.3.0
  - name: community.general
    version: 5.3.0
